navbar:
  blog_title: 轉職工程師，菜鳥爸紀錄
index:
  slogan:
    enable: true
    # Height ratio of banner image
    # Available: 0 - 100
    banner_img_height: 70
    # 为空则按 hexo config.subtitle 显示
    # If empty, text based on `subtitle` in hexo config
    text: "朝穿皮襖午穿紗，抱著兒子打代碼"
favicon: ./image/logo/cat-logo.png
#---------------------------
# 关于页
# About Page
#---------------------------
about:
  md_path: ./about/index.md
  banner_img: /image/logo/DSC_9935.JPG
  banner_img_height: 80  # available: 0 - 100
  avatar: ./image/logo/cat-logo.png
  name: Dean Yang
  intro: banner是可愛的鵝子，從醫療業轉職來，努力的補上許多基礎知識並多方發展，目前是朝著偏後端的全端走。
  icons:
   - { class: 'iconfont icon-github-fill', link: 'https://github.com/shengshengyang', tip: 'GitHub' }

post:
  mermaid:
    enable: true
    specific: false
    options:

custom_css:
  - /css/macBorder.css
  - /css/cloudedGlass.css
